### ISSUE TITLE
Provide Terms, Definitions and Complete Metadata for Data

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#10]
As a user, I should be able to go to a page that has a complete list of terms, definitions, and metadata for the development data.

>Create tooltips OR link to glossary to ensure that every specific field is define for the user, in filter panel, add data panel and legend. Field names defined in metadata from Sarah.

**Comment by ericyoungberg** [comment]
[FinalFieldsMetadata_120418.xlsx](https://github.com/MAPC/massbuilds/files/1939570/FinalFieldsMetadata_120418.xlsx)
