### ISSUE TITLE
Add nearest transit stop in project view on site

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#101]
The nearest transit stop is on the CSV download, but doesn't show up when you click on a development. I think this would be nice for the user to see once the project is in the database. It's not a user entered field.

**Comment by ericyoungberg** [comment]
@sannphilbrick I think I may have already fixed this.

<img width="1678" alt="capture d ecran 2018-06-14 a 10 05 38 am" src="https://user-images.githubusercontent.com/6749126/41417167-91454c78-6fba-11e8-9e25-8cb08588896c.png">

**Comment by iangmhill** [comment]
This appears to have been resolved by 872ed0ec29f55626c7f2b43944d58f0a09a89c90
