### ISSUE TITLE
Investigate IE compatibility 

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#103]
Site does not appear to show up in IE. If this is the case we should have a notice on the site saying that it's not compatible with IE and ask the user to download a different browser

**Comment by arouault** [comment]
Please check cross-browser compatibility. Eric says it *used* to be compatible. 
Upon investigation, regroup before refactoring or implementing notification.

**Comment by iangmhill** [comment]
Only partially resolved by #108. The page now loads, but there are still plenty of styling issues in IE.

**Comment by iangmhill** [comment]
Resolved by #116
