### ISSUE TITLE
Allow Users to Flag Incorrect or Old Development Data

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#11]
As a user I should be able to flag old or correct development data. Then as an administrator, I should see the flag and be able to ???. What should happen once data is flagged.

**Comment by mzagaja** [comment]
We need some additional information from the business stakeholders on this. Is this going to be a simple flag or do we need an entire model that has an entry that `belongs_to` a development and a user that has information about the flagged development?

**Comment by mzagaja** [comment]
@arouault Does this feature make sense to implement? Looking at the existing MassBuilds website it was used one time in the history of the site (two if you count a test by Tim). In my opinion, its purpose appears to largely be pre-empted/duplicated by the Edit suggestion feature which allows users to suggest changes to an existing development to make it correct. Something that is much more helpful for the moderators than being notified the development is generally wrong.

**Comment by TimReardon** [comment]
@mzagaja yes i think this still makes sense.  I don't think the flag was very easy to find before, with could explain its lack of use.  I think we need a way for folks to let us know the data is suspect or outdated, even if they don't have the information or inclination to actually make the necessary edits. these flags would be part of the data flow that interns consult weekly.

**Comment by mzagaja** [comment]
Roger that.

**Comment by arouault** [comment]
This lacks UX currently. @ericyoungberg needs to flesh out flagging for the end user.

**Comment by iangmhill** [comment]
@ericyoungberg can you link to the UX for this and related issue?
