### ISSUE TITLE
Latitude and Longitude Data Submitted with New Development is Incorrect After Changing Streetview

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#120]
To reproduce this bug create a new development and then type in an address, and then if you move the camera in street view farther down the street the lat and long associated with the new development will no longer reflect the address that we want.

The desired behavior is that the lat and long data being associated with the new development be the lat and long data calculated from the address when the new development page is initially loaded.

This needs to be tested for reproducibility. It was in progress so we need to identify whether there is a work in progress branch.

**Comment by mzagaja** [comment]
@allthesignals The thing says you added and then removed the ember label but it is still there. Maybe a GitHub bug. Wanted to ask if this is in fact an ember thing and if so if you want to take it? Otherwise I'll keep on my docket.

**Comment by allthesignals** [comment]
@mzagaja Hmmm I don't know why it did that. I believe it's an Ember bug, so I'll be taking a look at it. Thanks.

**Comment by allthesignals** [comment]
@mzagaja I went ahead and took out the streetview edit view for now, which #184 does... it seems like we wanted to take that out anyway, but maybe I'm mistaken.

I'm actually have some trouble reproducing this bug... what I'm see is that the streetview updates the `street_view_latitude` & `street_view_longitude`, but doesn't affect the actual `latitude` and `longitude` (they are separate fields). What's happening is the map view itself isn't updating the `latitude`/`longitude`. The only way to change that is to update the address. 

That's the behavior I'm seeing.

**Comment by allthesignals** [comment]
There is an issue with the binding. Getting the map component to update lat/long then ignores changes made to the address. For example, if the user re-geocodes an address, it won't update the map. Since Ember is all about _two way_ binding, and not one way, this could get tricky.

**Comment by allthesignals** [comment]
Maybe just need to wrestle with this: http://emberjs.com/api/classes/Ember.Binding.html#toc_one-way-bindings.
