### ISSUE TITLE
Add New Project Tags

### ISSUE THREAD

**Issue by allthesignals** [MAPC/massbuilds#152]
Users need project tags titled "Mixed Use", "Residential", "Commercial", and "40b".

**Comment by allthesignals** [comment]
The client now has the params, throws the following errors:
```
{title: "Param not allowed", detail: "forty-b is not allowed.", id: null, href: null, code: 105,…}
{title: "Param not allowed", detail: "mixed-use is not allowed.", id: null, href: null, code: 105,…}
{title: "Param not allowed", detail: "residential is not allowed.", id: null, href: null, code: 105,…}
{title: "Param not allowed", detail: "commercial is not allowed.", id: null, href: null, code: 105,…}
```

Something to note: Matt originally wanted these to be factored out into their own "programs" model, which exists now. I don't think it's in use. I think for now these are boolean fields on developments.

**Comment by allthesignals** [comment]
Looks like mixed_use already existed: https://github.com/MAPC/massbuilds/blob/develop/app/models/concerns/development/model_callbacks.rb#L39. Was it supposed to be computed from data?

**Comment by allthesignals** [comment]
@mzagaja will probably need your advice on this - one of the new project tags, mixed_use, is computed based on the values of `tothu` and `commsf`. Two options:

 - Remove computed model attribute and allow mixed used to manually configured regardless of other values
 - Allow it to be computed, update api to provide that information, but make changes to the UI which prevent users from trying to change mixed_use to something else (I'm not sure in Rails if a model attribute is defined with a method, it won't be treated as a normal ActiveRecord attribute that can be persisted to a database. In Ember, this is also the case). 

Moving on to the other fields for now.

**Comment by allthesignals** [comment]
Got an answer, mixed use is computed so going to go ahead with PR.

**Comment by arouault** [comment]
going to add a separate, related issue with these new tags - though they exist in editing view, they do not show up in filters on map search interface.
