### ISSUE TITLE
Occasionally Search Does Not Respond

### ISSUE THREAD

**Issue by allthesignals** [MAPC/massbuilds#156]
Occasionally when searching the API returns an Payload (Empty Content-Type) error when returning a 0. We need to further investigate what the cause of this is to create a reproducible test case.

**Comment by allthesignals** [comment]
Maybe related to #122, but searching an [address](http://www.massbuilds.com/developments/?placeSearch=60%20temple%20place%2C%20boston%2C%20ma) returns:
```
code: 103
detail: "60 temple place, boston, ma is not a valid value for id."
href: null
id: null
links: null
meta: null
source: null
status: "400"
title: "Invalid field value"
```

**Comment by allthesignals** [comment]
@mzagaja I'm going to hold off on this and #122 because they seem like API issues. Happy to pair on it to figure out the source of the issue (maybe it's the request itself, but seems unlikely).

**Comment by mzagaja** [comment]
@allthesignals is this fixed by 3b2974e or is it something different?

**Comment by allthesignals** [comment]
@mzagaja It's fixed, but Search by address is still wonky.

**Comment by mzagaja** [comment]
I would double check on the staging site because #193 might have fixed search by address.

**Comment by mzagaja** [comment]
Closing as fixed since I think "search by address" being wonky is a separate issue.
