### ISSUE TITLE
Staging Setup Issues

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#189]
- [x] Figure out a work around for the sub-domain issue. Heroku does not appear to allow for subsubdomains and therefore the app fails when attempting to contact http://stackoverflow.com/questions/17126729/subdomain-to-heroku-subdomain.
- [x] Get the database cloned for a staging instance. (E-mailed Susan)

**Comment by mzagaja** [comment]
The logs seem to suggest the 500 errors are a function of not having a working database, not a sub-sub-domain, so once I meet with Susan and sass out a path forward I should be able to have this up and working.

**Comment by mzagaja** [comment]
Ok now that the database issue has been resolved the sub-subdomain issue is still outstanding. Heroku gives a 404 error when it attempts to access api.massbuilds-staging.herokuapp.com. I am not sure how to configure sub-subdomains with Heroku and the documentation that I can pull via Google is non-existent. I have filed a support ticket with Heroku about this issue at https://help.heroku.com/tickets/439018 and am waiting to hear back on potential resolutions.

I also notice the console throws a Google Maps API error of the following variety:
```
Google Maps API error: RefererNotAllowedMapError https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: http://massbuilds-staging.herokuapp.com/developments/
```
I will need access to the Google API console or someone with that access to add this URL to the authorized referrers. Maybe @allthesignals has this?

**Comment by allthesignals** [comment]
@mzagaja I'll add it to the allowed list.

**Comment by mzagaja** [comment]
This was resolved in two parts. The first part is we created a CNAME record for staging.massbuilds.com and api.staging.massbuilds.com to point to the Heroku staging app. Then we configured Heroku to use those domains. Once we did the app worked without issues. We will need to do this going forward for any app that uses an api sub-domain.
