### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by iangmhill** [MAPC/massbuilds#197]
**Describe the feature. What should a user be able to do?**
The left panel should be open when a user visits the site for the first time. The panel should contain basic 'about' information for MassBuilds.

**Why do we need this feature?**
For new users, the purpose of MassBuilds can be unclear.

**Alternatives**
1. A separate page with this information
2. A modal that can be dismissed

**Comment by arouault** [comment]
**Content for modal:** 

Welcome to Massbuilds! 

Massbuilds is the Metropolitan Area Planning Council’s collaborative inventory of past, present and future real estate development projects. This tool provides governments, data analysts, urban planners, community advocates, and real estate developers with comprehensive data for thousands of projects across Massachusetts. 

- Filter and find development projects: Find the development data you need, filtering by neighborhood, municipality, construction status, affordable housing, units, square footage, project status, year of completion, developer name, and more!

- Contribute new data: Sign up to add new and existing real estate developments in your area. Entries are all verified by MAPC’s data team to ensure accurate, up to date information. 

- Export data: Export comprehensive raw development data into a spreadsheet or shapefile for further analysis.
