### ISSUE TITLE
Not Allowing New Developments

### ISSUE THREAD

**Issue by nicholasabbott96** [MAPC/massbuilds#202]
When I try to add a new development now, an error message reading "There was something wrong with the input. Either data is missing or invalid. See messages below:" pops up but there are no messages below and I have filled in all the required fields. This bug pops up about 15% of the time and pops up every time I try to add certain developments, but not when I try to add others.

**Comment by allthesignals** [comment]
@nicholasabbott96 can you give me a little more information about the data you're trying to enter? I know you keep a spreadsheet - maybe you could point to the row of data that causes this error? If it's throwing an error message, it's likely a 500 internal server error, rather than some javascript issue.

**Comment by nicholasabbott96** [comment]
Hey @allthesignals  - thanks for following up, the error isn't spreadsheet related, but rather when I (or theoretically anyone else) try to add a new development to MassBuilds on the site using the + button at the top of the page. For most developments (e.g. "West of Chestnut apartments") the process works fine, but when I try to add certain other developments (e.g. "Duxbury Landing" at the address 397 Washington St, Duxbury, MA), a message pops up saying "Missing or Invalid Data" followed by "There was something wrong with the input. Either data is missing or invalid. See messages below:" except there are not any messages below and I have filled out all of the required fields.  The problem does not appear to be time-related since I am able to enter other developments successfully immediately after, but the error message always pops up for Duxbury Landing and 15 other developments I've tried to enter so far, meaning it has to do with something that is being put into the fields themselves (my best guess is that it's related to the address).

**Comment by allthesignals** [comment]
@nicholasabbott96 thanks for the extra information - I'm guess I'm interested in exactly the data you're trying to enter so that I can reproduce the error and investigate. Does that make more sense? Thank you!

**Comment by nicholasabbott96** [comment]
@allthesignals Absolutely - the attached spreadsheet has additions that have been successfully added in green and additions that prompt the error message highlighted in yellow.
[Additions to MassBuilds.xlsx](https://github.com/MAPC/massbuilds/files/828453/Additions.to.MassBuilds.xlsx)

**Comment by nicholasabbott96** [comment]
Update: The problem only arises for new developments outside the inner ring. In other words, MassBuilds allows for new developments in Cambridge, Quincy, Boston, Waltham, etc., but for further out cities and towns an error message pops up when one attempts to add new developments. Matt Zagaja's hypothesis is that the auto-generation of the closest MBTA stop for each new development is triggering the error message because further out developments are not close to any MBTA stops. If possible, we should turn off the auto-generator of closest bus stop for all developments or at the very least for developments outside of the inner ring, at which point hopefully the site will allow for the addition of new developments regardless of proximity to Boston.
