### ISSUE TITLE
Humanizing sharing link breaks filter query

### ISSUE THREAD

**Issue by iangmhill** [MAPC/massbuilds#204]
**Describe the bug**
Removing ugly url artifacts like brackets from the sharing link breaks the filtering when the link is used.

**Steps to reproduce**
1. Filter developments for multiple municipalities (or another filter with more than one of the same type)
2. Your url should end with something like `/map?municipal[]=Cambridge&municipal[]=Somerville`
3. Copy that link using the share button
4. You'll end up with something like `http://localhost:4200/map?municipal=Cambridge&municipal=Somerville` **Notice the lack of brackets**
5. Attempt to use the sharing link
6. Notice that the developments are only filtered by the last entry (in this case Somerville). The filter ignores the earlier parameter

**Expected behavior**
We should probably leave the brackets in there so the filter actually works.

**Comment by ericyoungberg** [comment]
Interesting. The way I was serializing the URL before would create `http://localhost:4200/map?municipal=Cambridge,Somerville`

**Comment by ericyoungberg** [comment]
Something must've been changed. I think we should still use serialized URLs.

**Comment by iangmhill** [comment]
`/map?municipal=Cambridge,Somerville` works for me, so something must have changed in how we generate those links.

**Comment by ericyoungberg** [comment]
Yeah, probably won't be a big lift.
