### ISSUE TITLE
Differences in estimated date of completion

### ISSUE THREAD

**Issue by nicholasabbott96** [MAPC/massbuilds#204]
As far as I can tell, the estimated end date for all developments listed on the initial development page on massbuilds is listed as 2016 (e.g. "Completed (est. 2016)" or "Planning (est. 2016)"), but when I go to edit each development the correct estimated date of completion is listed and the correct date also shows up when I download the data/export results.

**Comment by allthesignals** [comment]
Looks like those dates were just filler in the template: https://github.com/MAPC/massbuilds/blob/develop/app/views/developments/show/_status.html.haml. 

We just have to make them dynamic. Easy fix.
