### ISSUE TITLE
Add beta sticker and contact info Website

### ISSUE THREAD

**Issue by nicholasabbott96** [MAPC/massbuilds#207]
We need to add a tag/banner to the site that designates that it is in beta testing. There also needs to be a visible place for users that tells them to contact massbuilds@mapc.org with any inquiries or problems, but it is worth asking Alicia what specifically she wants that to say/where she wants it to appear on the site. There is already a "contact us" button at the bottom of the massbuilds.com homepage, but perhaps explicitly listing that email there and/or moving that tab further up the page so its more visible might be preferable as well.

**Comment by nicholasabbott96** [comment]
In addition, please add an FAQ tab which then lists the questions and answers found in the attached document (if attachment doesn't work it's "MassBuilds FAQs_v2.docx" in the Projects>Current Projects>Development Database folder.
[Massbuilds FAQs_v2.docx](https://github.com/MAPC/massbuilds/files/868245/Massbuilds.FAQs_v2.docx)

**Comment by mzagaja** [comment]
Going to give this to @allthesignals since it is a front-end task. Happy to pick it up later as part of me learning ember (which has to occur eventually) but right now a little trigger shy doing things to the Ember templates without fully understanding what I'm doing in that arena.

**Comment by sannphilbrick** [comment]
@allthesignals I'm not sure how to prioritize issues in github, but besides getting MassBuilds to work in IE, this is the next top priority. I think it would alleviate a lot of emails we wind up fielding
