### ISSUE TITLE
Duplicate Bostons in filter panel

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/massbuilds#209]
**Describe the bug**
There two entries for Boston in the filter panel's "Town/City" subpanel. This doesn't effect the functionality, just might be confusing for users to see two Bostons.

**Steps to reproduce**
Walk us through how you revealed the bug.
1. Open filter panel
2. Select "Town/City" tab
3. Search for Boston

**Expected behavior**
There should only be one

**Screenshots**

<img width="456" alt="capture d ecran 2018-07-12 a 1 49 45 pm" src="https://user-images.githubusercontent.com/6749126/42650790-5a2ac042-85db-11e8-9dfe-3fb6baedc674.png">

**Comment by iangmhill** [comment]
Resolved by fixing one development which listed its `municipal` as `'Boston '` with a space at the end.
