### ISSUE TITLE
Remove Matt Cloyd's email address from the "email them directly" link

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#219]
Sometimes when you click on a project an error pops up saying "Something broke, but we're looking into it. (This one's on us.). there's an option to email the developers directly to "let them know what was going on when this happened."

Right now the link pops open an email to Matt Cloyd and Matt Gardner. This should be changed to Matt Z and Matt G or a general massbuilds email

**Comment by mzagaja** [comment]
Fixed in https://github.com/MAPC/massbuilds/commit/0e14f5d9cfad5cc2d2fa275543db11c8c1d2d17d
