### ISSUE TITLE
Export filter only works with some filters

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#237]
**Describe the bug**
I tried to export a csv earlier today with projects only having >200 housing units, but the csv I downloaded contained all projects. If I filter with a municipality and download the csv, the file is only projects within that municipality 

**Steps to reproduce**
Walk us through how you revealed the bug.
1. Filter projects by number of housing units
2. download csv
3. See how many projects there are 

**Expected behavior**
I expected whatever filter I have on my map applied to the projects that are in the downloaded file 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: windowns
 - Browser chrome

**Comment by iangmhill** [comment]
Resolved by #239
