### ISSUE TITLE
can't close out of welcome screen on mobile device

### ISSUE THREAD

**Issue by arouault** [MAPC/massbuilds#247]
From a user: 

"Just noticed something on MassBuilds while trying to log in on my phone: the opening "Welcome to MassBuilds" blocks the screen, and I can't x out it! It's an iPhone 6s, if that makes a difference"

![image](https://user-images.githubusercontent.com/1305629/43270090-3e6bb130-90c2-11e8-8fa5-7f767f7baf54.png)

**Comment by mzagaja** [comment]
Duplicate of #281
