### ISSUE TITLE
Shapefile Download not working

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#261]
**Describe the bug**
When the user clicks to download a shapefile of the development information they're given the following error:
"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome (and tested in IE)

**Comment by mzagaja** [comment]
Closing this as it does not reproduce as of today in Citrix + latest Chrome. Likely was fixed and not marked as such, or was a temporary server issue two years ago.
