### ISSUE TITLE
Not able to see moderation panel

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#263]
**Describe the bug**
When I click on "Moderations" on the right hand panel after logging in, nothing comes up and the url does not change from https://www.massbuilds.com/map

**Steps to reproduce**
Walk us through how you revealed the bug.
1. Go to menu
2. Click on moderations
3. See error

**Expected behavior**
I expect for a pane to show up on the left side of my screen with projects to moderate

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  chrome

**Comment by ericyoungberg** [comment]
This was an issue with Passenger being overloaded
