### ISSUE TITLE
Add Developments: Save Not Working

### ISSUE THREAD

**Issue by theryankelly** [MAPC/massbuilds#264]
**Describe the bug**
Call from Medfield Town Planner. They are entering developments (69-71 North St. Medfield)  (Hillside Village, Meadows Road), but is **unable to save**.   While logged in, is able to add info and hit close and save button, but can't hit submit for review.  Developments are not showing up under "My Developments" section.  .

**Expected behavior**
Should be able to save edits.  Has more developments to add in.

**Desktop (please complete the following information):**
Windows
Chrome

**Additional context**
Has entered places in the past, although they all say authored by MAPC Staff. Sending over a spreadsheet of data being entered.

**Comment by ericyoungberg** [comment]
Discovered to be a data entry issue: a few of the boxes that required `0` were left empty. The orange empty-but-required field indicator was functioning properly, but was not interpreted by the user as the source of their malfunction. 

Figuring out a way of more clearly indicating data entry requirements maybe a worthwhile future enhancement to look into.

**Comment by smithWEBtek** [comment]
This is not a matter of data entry. The current Ember form recalls the data that was entered and saved, but does not actually submit the full dataset when attempting to "Submit for Review".  It only submits that changed data, and then Rails validations fail the post request because of missing data.
