### ISSUE TITLE
Speed up Moderation Panel loading or add "loading" message

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#267]
**Describe the bug**
When the user clicks on "moderation" the left panel takes roughly 60 seconds to load without any indication the system is "working on it" 

**Steps to reproduce**
Click "moderation"
Wait

**Expected behavior**
I expected the moderation panel to show up within 10 seconds or see a "loading" screen

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by sannphilbrick** [comment]
This is an ongoing issue that appears to be getting worse. Loading of moderation page either doesn't happen or takes ~2 min to show up with no notice to user that it is 'pending'

**Comment by sannphilbrick** [comment]
Flagging this again. I've tried over the past two days and the moderation page won't show up at all for me.

**Comment by mzagaja** [comment]
MassBuilds seems to make a network request for each item in the `edits` table. This network request comes from the front-end client (ember) portion of the application, but currently not sure where nor why this occurs. However I can now reproduce this locally by doing a pg_restore of the production database into my local copy and making sure to include the edits table.

```sh
pg_dump -Fc -h pg.mapc.org -d massbuilds -p 5432 -U massbuilds > massbuilds-2020-10-28.dump
pg_restore -a -d massbuilds_development -O -t users -t developments ../massbuilds-2020-10-28.dump
pg_restore -a -d massbuilds_development -O -t edits ../massbuilds-2020-10-28.dump
```
