### ISSUE TITLE
Splash Welcome: Unable to Navigate on iPhone

### ISSUE THREAD

**Issue by theryankelly** [MAPC/massbuilds#281]
**Describe the bug**
The "Welcome to MassBuilds" splash article does not fit on some mobile screens, making it unnavigable.  We need to give the user a path to the site.

**Steps to reproduce**
Produced on BrowserStack
- iPhone SE (chrome)
- Nexus 5 (chorme)

**Expected behavior**
The "Continue to MassBuilds" or "X" to close must be clickable for the user.  The welcome screen should either fit to screen size or be paired down on small screens.

**Screenshots**
![Screen Shot 2020-02-24 at 12 58 25 PM](https://user-images.githubusercontent.com/2421382/75178525-3e9b3200-5706-11ea-977c-0d4277392bd1.png)

![Screen Shot 2020-02-24 at 1 14 45 PM](https://user-images.githubusercontent.com/2421382/75179314-cfbed880-5707-11ea-9312-c36972f38164.png)

**Additional context**
We may consider moving the **Filter and find development projects**, **Contribute new data**, **Export data** highlights to pop up tutorial upon first navigation

**Comment by mzagaja** [comment]
Also filed in #247 which I will close.
