### ISSUE TITLE
Return points with development data associated attached

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/massbuilds#30]
Points should be returned with the following development data associated:

- Title
- Full Address
- Status
- Developer Name

The endpoint should support grabbing all points and points within a bounding box where I pass query parameters leftLat, leftLng, rightLat, rightLng

**Comment by mzagaja** [comment]
How do you want points returned? A single key with WKT or a lat and long key with appropriate values or some other way?

**Comment by ericyoungberg** [comment]
It should just be a development model but only with those values. So according to the current schema it will be a latitude and longitude attribute.

**Comment by ericyoungberg** [comment]
I could hit the the GET endpoint on the developments controller and pass a param like 'trunc=true'

**Comment by mzagaja** [comment]
The lat/long columns are legacy, I was thinking of getting rid of them at some point but could also just create accessor methods that map to the column with the point value and return those keys.

**Comment by ericyoungberg** [comment]
That would be helpful because leaflet doesn't accept point value; leaflet would rather have lat/lng.

**Comment by mzagaja** [comment]
We do not currently have a "developer_name" attribute in the table. See https://raw.githubusercontent.com/MAPC/massbuilds/develop/rails/lib/import/developments.csv for a list of available attributes for import.

**Comment by ericyoungberg** [comment]
#32, #33
