### ISSUE TITLE
New Developments Should POST Lat/Long From Client Side

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#35]
I've been thinking about the implementation of getting the POINT from the address and after debating the merits of doing it on the back end I think from a user perspective it would be better to have the client grab this and then POST it to the back end. The reason being that the user probably wants to see their new development on the map immediately and so doing an `after_save` hook in rails will potentially not retrieve the point in time to display to the user when their view changes. See https://github.com/MAPC/massbuilds/issues/15#issuecomment-352878597 for a description of what geocoder to use. Let me know if this makes sense to you or if you have other ideas on this.

**Comment by ericyoungberg** [comment]
Implemented as #62
