### ISSUE TITLE
Add in parcel_fy field

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#41]
We should store the calculated fiscal year in the parcel_fy field. @TimReardon how do we calculate what the fiscal year is? Is it just July 1 to July 1 of the year the development is added to the database?

**Comment by TimReardon** [comment]
@mzagaja i think the intent here was simply to report the FY vintage of any parcel/assessor data that is attached to the record (LOC_ID at the very least, possibly others)--there's no need to do more calculations, unless i am missing something @sannphilbrick ?

**Comment by sannphilbrick** [comment]
@TimReardon's correct. This is simply to report the FY vintage of the parcel data, which is a field in the parcel database. associated with each parcel (but I believe it's the same across all parcels in a muni)

**Comment by iangmhill** [comment]
Can be housed in the FAQ. Not necessary in interface.

**Comment by iangmhill** [comment]
Resolved by #130
