### ISSUE TITLE
Postgres FDW Fails to Create Appropriate User Mapping

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#76]
In the creation of the foreign data wrapper https://github.com/MAPC/massbuilds/blob/develop/rails/lib/tasks/db.rake#L5 fails in a rake task despite the fact the raw SQL works.

**Comment by ericyoungberg** [comment]
I think we can close this one as we found that the real issue was that the firewall in _pg_hba.conf_ was missing an entry.
