### ISSUE TITLE
Implement Search Feature

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#8]
As a user I should be able to search by geography or keyword with intuitive UX.

Need to decide what we will use the search engine. Matt will look into how much search capability we have within Postgres natively that we can expose for this purpose or if we need to use a specialized search app like Elasticsearch.

The front end component of this needs some user research and further discussion with the product owner and client.

**Comment by mzagaja** [comment]
I think at this point that Postgres native search functionality is sufficient here. Folks seem to have done PostGIS searching (see https://alternatelabs.co/blog/search-by-proximity-using-postgis) but also there is a [well maintained full-text search gem](https://github.com/Casecommons/pg_search) from Casecommons. I think this could be a good path.

**Comment by mzagaja** [comment]
There is a large menu of options for setting up PG_Search for searching our development list. I need to figure out what our approach should be. Also need to figure out how to take the appropriate parameters or other things we will expose to the user from the ember front end.

**Comment by arouault** [comment]
Geographies for Search Inclusion:

- Official City or Town Name
- Keyword / name of development
- street address
