### ISSUE TITLE
Add data by dropping a point on the map (not only addresses) 

### ISSUE THREAD

**Issue by arouault** [MAPC/massbuilds#88]
Not all points fall on existing addresses. Point data should be modifiable on the map during data entry.

**Comment by ericyoungberg** [comment]
If I'm going to implement this, I may as well add geocoding addresses on the fly as well.

**Comment by sannphilbrick** [comment]
Note: this becomes an issue with some large/high profile projects like Wynn Boston Harbor (now Encore Boston Harbor). The point was dropped in the middle of Everett, far away from the actual location of the casino and there's no way to edit it right now.

**Comment by ericyoungberg** [comment]
Duplicate #105
