### ISSUE TITLE
Reduce zoom level after closing panel

### ISSUE THREAD

**Issue by arouault** [MAPC/massbuilds#90]
After closing information panel on a point, limit zoom to municipality last viewed

**Comment by TimReardon** [comment]
I would suggest keep zoom at current extent. even zooming out to Muni would require one to zoom back into the neighborhood one was viewing.

**Comment by arouault** [comment]
This is the issue we discussed in person yesterday, where when you close out of the panel, the map zooms out to the full region view.

My suggestion is to limit the zoom to the municipality (not the regional view) after closing the panel. Is your suggestion @TimReardon that zoom should be at the neighborhood level upon closing the panel? (Currently it zooms out to the regional scale).

**Comment by arouault** [comment]
@ericyoungberg please validate our interpretation of how this should work with @TimReardon

**Comment by ericyoungberg** [comment]
Closed by https://github.com/MAPC/massbuilds/pull/114
