### ISSUE TITLE
Can't create developments with "In Construction" status

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/massbuilds#94]
You are able to edit developments that already have the status along with change any development to have that status, but you are not able to create a development with that status.

**Comment by sannphilbrick** [comment]
As follow-up, I was able to create a project with an in-construction status on 5/25 (114 Brookside Ave)

**Comment by arouault** [comment]
Try to reproduce error. Test across browsers. Validate whether this is a user error or not.

**Comment by iangmhill** [comment]
I haven't been able to reproduce this either in Chrome. There are styling issues in IE and Firefox that prevent me from testing it there. I'm going to elevate those issues to high priority and circle back to this.

**Comment by arouault** [comment]
No one can reproduce this. user error.
