### ISSUE TITLE
Remove employment estimate fields and values.

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#99]
For projects where the user doesn't enter employment, a formula should be implemented that calculates estimated employment by employees per sqft for each type of square footage. These are formulas Research uses in their work and can be easily given to the digital team. If this is not a feature we're adding, we should remove the field from the csv download

**Comment by arouault** [comment]
Will require coordination with @sannphilbrick to get your algorithm for calculating this. 

Also requires decision from @TimReardon on "Do we want estimated employment in the interface?"

**Comment by iangmhill** [comment]
Generalized estimates of employment shouldn't be published. Take out the check box and field for this data point.

**Comment by sannphilbrick** [comment]
@mzagaja right now there is an estemp and rptdemp field (estimated employment and reported employment). We should combine these into one employment field. I currently like that rptemp is black if there is no value, not zero (like estemp). To create the updated field I would take the value already in rptdemp. If that value is 0 or null and the value in estemp is >0, the 0 or null value should be replaced with the value in estemp. After that estemp can be deleted, but we may want to change the name of rptdemp to just emp
